site_name: Portfolio
repo_url: https://github.com/mrmattkennedy/TH-Medical-Charges
repo_name: MattKennedy-Website

theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  features:
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

  icon:
    logo: octicons/paper-airplane-24

  # font:
  #   text: Bungee
    
plugins:
  - mkdocs-jupyter
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags:
      enabled: true

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.pathconverter 
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: material/email 
      link: mailto:mdkennedy03@gmail.com

extra_css:
  - stylesheets/extra.css

## Page tree
nav:
- Home: index.md
- Exploring medical bills across an individual's features: insurance_charges.md
- Working with semantics and parts-of-speech for non-canonical data: cs447.md
- Analyzing census populations : census.ipynb


